Header header
float64 BackTime_i
float64 BackTime_j
geometry_msgs/Vector3 bias_acc_i
geometry_msgs/Vector3 bias_gyro_i
geometry_msgs/Vector3 bias_acc_j
geometry_msgs/Vector3 bias_gyro_j
geometry_msgs/Vector3 gyr_0_i
geometry_msgs/Vector3 acc_0_i
geometry_msgs/Pose pose_j
geometry_msgs/Vector3 velocity_j
geometry_msgs/Pose pose_i
geometry_msgs/Vector3 velocity_i
add_msg/Intervalimu[] imu_raw_info

