%YAML:1.0

output_path: "/gazebo_ws/src/libcppt/config/log.tum"

model_type: PINHOLE
image_width: 640
image_height: 480

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning.

#If you choose 0 or 1, you should write down the following matrix.
#camera calibration
T_BC0: !!opencv-matrix
    rows: 4
    cols: 4
    dt: d
    data: [0.00108605, 0.178367,   -0.983963, -0.221,
           0.999999, -0.00108605, 0.000906879, 0,
           -0.000906879,  -0.983963,  -0.178368, 0.856,
           0.0, 0.0, 0.0, 1.0]

intrinsics0: [554.254691191187, 554.254691191187, 320.5, 240.5] #fu, fv, cu, cv
distortion_coefficients0: [0, 0, 0, 0]

T_BI: !!opencv-matrix
    cols: 4
    rows: 4
    dt: d
    data: [1.0, 0.0, 0.0, 0.0,
           0.0, 1.0, 0.0, 0.0,
           0.0, 0.0, 1.0, 0.0,
           0.0, 0.0, 0.0, 1.0]

acc_n: 0.1         # accelerometer measurement noise standard deviation. #0.599298904976
gyr_n: 0.01        # gyroscope measurement noise standard deviation.     #0.198614898699
acc_w: 0.001       # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 0.0001      # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.81007    # gravity magnitude

#feature traker paprameters
clahe: 3.0              # 0 -> disable. others -> enable, and value is clipLimit parameter.
fast_threshold: 15      # FAST corner threshold
min_dist: 32            # min distance between two features
F_threshold: 3.0        # ransac threshold (pixel)

#backend parameters
max_solver_time_in_seconds: 0.05  # max solver itration time (ms), to guarantee real time
max_num_iterations: 10            # max solver itrations, to guarantee real time
keyframe_parallax: 10.0           # keyframe selection threshold (pixel)
cv_huber_loss_parameter: 1.0      # HuberLoss
sliding_window_size: 10
triangulate_default_depth: 5.0    # (m)
max_imu_sum_t: 10.0               # (s)
min_init_stereo_num: 30

#reloc parameters
enable_reloc: 1                    # start loop closure
#load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
#fast_relocalization: 0             # useful in real-time and large project
#pose_graph_save_path: "/home/tony-ws1/output/pose_graph/" # save and load path

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#rolling shutter parameters
#rolling_shutter: 0                  # 0: global shutter camera, 1: rolling shutter camera
#rolling_shutter_tr: 0               # unit: s. rolling shutter read out time per frame (from data sheet).

#visualization parameters
#save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0
#visualize_imu_forward: 0        # output imu forward propogation to achieve low latency and high frequence results
#visualize_camera_size: 0.4      # size of camera marker in RVIZ

voc_path: "/gazebo_ws/src/libcppt/config/voc/brief_k10L6.bin"
brief_pattern_path: "/gazebo_ws/src/libcppt/config/brief/brief_pattern.yml"

enable_pose_faster: 0            # pose will align with imu fps
depth_units: 1              # depth image conversion scale (16UC1 -> m)
